# Generated by Django 5.1.3 on 2024-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_plato_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
