# Generated by Django 5.1.3 on 2024-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_alter_plato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='procedencia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
